
version: '2.1'
services:
  mariadb102:
    extends:
      file: docker-compose-base.yml
      service: base-mariadb102
    container_name: ${INSTANCE_NAME:-mariadb102}.${INSTANCE_DOMAIN:-local}
    hostname: ${INSTANCE_NAME:-mariadb102}.${INSTANCE_DOMAIN:-local}
    network_mode: bridge
    ports:
    - "${MARIADB_3306_PORT:-3306}:3306"
    - "${MARIADB_5444_PORT:-5444}:5444"
    - "${MARIADB_5567_PORT:-5567}:5567"
    - "${MARIADB_5568_PORT:-5568}:5568"
    volumes:
    - data:/var/lib/mysql

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data
      o: bind
