
version: '2.1'
services:
  mysql57:
    extends:
      file: docker-compose-base.yml
      service: base-mysql57
    container_name: ${INSTANCE_NAME:-mysql57}.${INSTANCE_DOMAIN:-local}
    hostname: ${INSTANCE_NAME:-mysql57}.${INSTANCE_DOMAIN:-local}
    network_mode: bridge
    ports:
    - "${SERVER_PORT:-3306}:3306"
    volumes:
    - data:/var/lib/mysql

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data
      o: bind
