
version: '2.1'
services:
  mysql57-develop:
    extends:
      file: docker-compose-base.yml
      service: base-mysql57
    container_name: ${INSTANCE_NAME:-mysql57}.${INSTANCE_DOMAIN:-local}
    hostname: ${INSTANCE_NAME:-mysql57}.${INSTANCE_DOMAIN:-local}
    networks:
      local-network:
        ipv4_address: 172.16.238.57
        ipv6_address: 2001:3984:3989::57
    ports:
    - "${SERVER_PORT:-3306}:3306"
    volumes:
    - data:/var/lib/mysql

networks:
  local-network:
    external: true
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
      - subnet: 2001:3984:3989::/64

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data
      o: bind
