
version: '2.1'
services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile
    command: [--character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci]
    container_name: ${MYSQL_DOMAIN:-mysql}.${INFRASTRUCTURE:-local}
    environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root_pass} # changeme
    - MYSQL_USER=${MYSQL_USER:-user} # changeme
    - MYSQL_PASSWORD=${MYSQL_PASSWORD:-user_pass} # changeme
    - MYSQL_DATABASE=${MYSQL_DATABASE:-db}
    hostname: ${MYSQL_DOMAIN:-mysql}.${INFRASTRUCTURE:-local}
    image: ${DOCKER_REGISTRY:-home1oss}/mysql:5.6.31
    # --net=host in order to be able to connect from outside of docker
    #network_mode: host
    ports:
    - "3306:3306"
    volumes:
    - volume-mysql:/var/lib/mysql

volumes:
  volume-mysql: {}

#networks:
#  default:
#    external:
#      name: oss-network
