
version: '2.1'
services:
  base-mysql56:
    build:
      context: .
      dockerfile: Dockerfile
    command: [--character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci]
    environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root_pass} # changeme
    - MYSQL_USER=${MYSQL_USER:-user} # changeme
    - MYSQL_PASSWORD=${MYSQL_PASSWORD:-user_pass} # changeme
    - MYSQL_DATABASE=${MYSQL_DATABASE:-db}
    image: ${IMAGE_PREFIX:-home1oss}/mysql:${IMAGE_TAG:-5.6.40}
    restart: always
