
version: '2.1'
services:
  mariadb101:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_REGISTRY:-home1oss}/mariadb:10.1.22
    restart: always
    container_name: ${MYSQL_DOMAIN:-mariadb}.${INFRASTRUCTURE:-local}
    environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root_pass} # changeme
    hostname: ${MYSQL_DOMAIN:-mariadb}.${INFRASTRUCTURE:-local}
    ports:
    - "${MARIADB_3306_PORT:-3306}:3306"
    - "${MARIADB_5444_PORT:-5444}:5444"
    - "${MARIADB_5567_PORT:-5567}:5567"
    - "${MARIADB_5568_PORT:-5568}:5568"
    volumes:
    - volume-mariadb101:/var/lib/mysql

networks:
  default:
    external: true
    name: oss-network

volumes:
  volume-mariadb101: {}
